version: "3"

services:

  weather_api:
    container_name: weather_api
    build: ./weather_api
    # Uncomment for non socket API
    #ports:
    #  - "5000:5000"
    volumes:
      - ./weather_api:/weather_api
      - /var/www/api:/var/www/api
    restart: always
    environment:
      - CACHE_TTL=300
      - DEFAULT_MAX_NUMBER=10
      - API_KEY=eba947a9dee289afd7c463fcfe3d99d1
